// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnZoBi6LaZ8m5Pyl0EOm6xil9pFjlpC30',
    appId: '1:524949285148:web:a772bee33f3243d07db2d9',
    messagingSenderId: '524949285148',
    projectId: 'firestore-e6b58',
    authDomain: 'firestore-e6b58.firebaseapp.com',
    storageBucket: 'firestore-e6b58.appspot.com',
    measurementId: 'G-JPYLXXV5JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBytaI-T2_EmfUxgVCjKO2XodPAR6jIWTI',
    appId: '1:524949285148:android:c2ace01c152c09a17db2d9',
    messagingSenderId: '524949285148',
    projectId: 'firestore-e6b58',
    storageBucket: 'firestore-e6b58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbZBG2RKb3GeBXqE5dTjEvxWBMGAgA_sE',
    appId: '1:524949285148:ios:f43426c967c9a3247db2d9',
    messagingSenderId: '524949285148',
    projectId: 'firestore-e6b58',
    storageBucket: 'firestore-e6b58.appspot.com',
    androidClientId: '524949285148-tcc84dmo2u8dgc68qn11vc87d24l11ib.apps.googleusercontent.com',
    iosClientId: '524949285148-sbkhkulul7r75tetmnuqqmpefp5bhpdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbZBG2RKb3GeBXqE5dTjEvxWBMGAgA_sE',
    appId: '1:524949285148:ios:f43426c967c9a3247db2d9',
    messagingSenderId: '524949285148',
    projectId: 'firestore-e6b58',
    storageBucket: 'firestore-e6b58.appspot.com',
    androidClientId: '524949285148-tcc84dmo2u8dgc68qn11vc87d24l11ib.apps.googleusercontent.com',
    iosClientId: '524949285148-sbkhkulul7r75tetmnuqqmpefp5bhpdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestore',
  );
}
